# Generated by Django 2.2.1 on 2019-07-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='config',
            field=models.TextField(default='[server]\nport=13353\nrevision=4321\npak=pak128\nsave=example.sve\nlang=en\n'),
        ),
    ]
