# Generated by Django 2.2.1 on 2019-07-09 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_instance_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='config',
        ),
    ]
