# Generated by Django 2.2.3 on 2019-07-13 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0002_auto_20190713_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='pak',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='instances.Pak'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='save',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='instances.Save'),
        ),
    ]
