# Generated by Django 2.2.3 on 2019-07-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0003_auto_20190713_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instance',
            old_name='save',
            new_name='savegame',
        ),
    ]
