# Generated by Django 2.2.3 on 2019-07-27 16:29

import django.core.validators
from django.db import migrations, models
import instances.models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0004_auto_20190713_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='debug',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='pak',
            name='file',
            field=models.FileField(upload_to=instances.models.pak_file_path),
        ),
        migrations.AlterField(
            model_name='save',
            name='file',
            field=models.FileField(upload_to=instances.models.save_file_path),
        ),
    ]
